# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-21 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('facebook_id', models.CharField(default='me', help_text="Use 'me' to view your own posts", max_length=100, verbose_name='Facebook ID')),
                ('token', models.CharField(blank=True, max_length=500, verbose_name='Access token')),
                ('token_type', models.CharField(blank=True, max_length=200, verbose_name='Token type')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
            ],
            options={
                'verbose_name': 'access',
                'verbose_name_plural': 'accesses',
            },
        ),
    ]
